config/routes.rb
Rails.application.routes.draw do
  
  devise_for :employees
  get 'employeedetails', to: "employee_details#new"
  post 'employeedetails', to: "employee_details#create"

  get 'zensark', to: 'zensark#home'
  
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root 'pages#home'
end

app/models/address.rb
class Address < ApplicationRecord
  belogns_to :employee  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :employee
end

app/models/designation.rb
class Designation < ApplicationRecord
  has_many :employees, through: :employee_details
end

app/models/employee.rb
class Employee < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_one :employee_detail
  has_many :addresses
  has_many :attendances
  has_many :employee_leave
  has_many :leaves, :through=> :employee_leaves
  has_one :designation, :through=> :employee_detail
  has_many :employee_projects
  has_many :projects, :through=> :employee_projects
  has_one :role
end

app/models/employee_detail.rb
class EmployeeDetail < ApplicationRecord
  belongs_to :employee, optional: true
  belongs_to :project, optional: true
  belongs_to :designation, optional: true
end

app/models/employee_leafe.rb
class EmployeeLeafe < ApplicationRecord
  belongs_to: employee
  has_one: leave
end

app/models/employee_project.rb
class EmployeeProject < ApplicationRecord
end

app/models/leafe.rb
class Leafe < ApplicationRecord
  belongs_to: employee
end

app/models/project.rb
class Project < ApplicationRecord
  # has_many: employees
  has_many :employee_projects
  has_many :employees, :through=> :employee_projects
end

app/models/role.rb
class Role < ApplicationRecord
  belongs_to :employee, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller? 

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :role_id, :employee_id])
  end

  def after_sign_in_path_for(resource)
    if current_employee
      zensark_path
    else  
      render root_path
    end
  end

  
  
  
end

app/controllers/employee/registrations_controller.rb
# frozen_string_literal: true

class Employee::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  before_action :configure_account_update_params, only: [:update]
  

  #GET /resource/sign_up
  def new
    super
  end

  #POST /resource
  def create
    super
  end

  #GET /resource/edit
  def edit
    super
  end

  #PUT /resource
  def update
    super
  end

  #DELETE /resource
  def destroy
    super
  end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  def cancel
    super
  end




  #If you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
    devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute, :first_name, :last_name])
    #params.require(:employee).permit(:first_name, :last_name)
  end

  #If you have extra params to permit, append them to the sanitizer.
  def configure_account_update_params
    devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  end

  #The path used after sign up.
  def after_sign_up_path_for(resource)
    super(resource)
  end

  #The path used after sign up for inactive accounts.
  def after_inactive_sign_up_path_for(resource)
    super(resource)
  end
end

app/controllers/employee_details_controller.rb
class EmployeeDetailsController < ApplicationController
  def new 
    @mf = EmployeeDetail.new()
  end

  def create 
    @mf = EmployeeDetail.new(edparams)
    @mf.save
    render plain: @mf.errors.inspect
  end

  def edparams 
    params.permit(:contact_no, :emplyee_id, :emergency_contact_no, :designation_id, :manager_id, :blood_group, :project_id, :experience)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/zensark_controller.rb
class ZensarkController < ApplicationController
  before_action :check_route
  def home
    @attendances = Attendance.where("login > ? AND logout < ?", Date.today-7, Date.today-1)
  end

  def check_route 
    if current_employee 
       zensark_path
    else  
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employee_details_helper.rb
module EmployeeDetailsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/zensark_helper.rb
module ZensarkHelper
end

app/views/employee_details/new.html.erb
<div class="employee-details-main-container">
  <div class="employee-details-sub-container">
    <h1 class="employee-details-heading">Employee detalis</h1>
    <%= form_with model: @emplyee_details do |f| %>
      <div class="employee-details-inputs-main-container">
        <div>
          <div class="field">
            <%= f.label :contact_no %><br />
            <%= f.number_field :contact_no, autofocus: true, autocomplete: "contact-no" %>
          </div>

          <div class="field">
            <%= f.label :emergency_contact_no %><br />
            <%= f.number_field :emergency_contact_no, autofocus: true, autocomplete: "emergency-contact_no" %>
          </div>

          <div class="field">
            <%= f.label :designation_id %><br />
            <%= f.number_field :designation_id, autofocus: true, autocomplete: "designation" %>
          </div>

          <div class="field">
            <%= f.label :emplyee_id, "Employe Id" %><br />
            <%= f.number_field :emplyee_id, autofocus: true, autocomplete: "emplyee-id" %>
          </div>
        </div>
        <div>
          <div class="field">
            <%= f.label :manager_id, "Manager Id" %><br />
            <%= f.number_field :manager_id, autofocus: true, autocomplete: "manager-id" %>
          </div>

          <div class="field">
            <%= f.label :blood_group, "Blood Group" %><br />
            <%= f.text_field :blood_group, autofocus: true, autocomplete: "blood-group" %>
          </div>

          <div class="field">
            <%= f.label :project_id, "Project Id" %><br />
            <%= f.number_field :project_id, autofocus: true, autocomplete: "project-id" %>
          </div>

          <div class="field">
            <%= f.label :experience, "Expirence" %><br />
            <%= f.number_field :experience, autofocus: true, autocomplete: "experience" %>
          </div>
        </div>
      </div>

      <div class="actions employee-details-submit-button-container">
        <%= f.submit "Add" %>
      </div>

    <% end %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="">
  <footer class="custom-footer">
    <small class="text-white">Copyright &copy; <%= link_to "Zensark Technologies", "https://zensark.com", class: "text-white" %></small>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div>
  <% if notice %>
    <p class="alert alert-success"><%= notice %></p>
  <% end %>

  <% if alert %>
    <p class="alert alert-danger"><%= alert %></p>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar-sub-container">
    <div class="title-container">
      <a href="/">
        <img class="logo" src="https://zensark.com/zensark2/wp-content/uploads/2021/01/Asset-16.png"/>
      </a>
    </div>
    <div class="buttons-container">
      <% if current_employee %>
        <%= button_to "Logout", destroy_employee_session_path, class: "logout", method: :delete%>
      <% else%>
        <% if request.path.split("/").last == 'sign_in' || request.path.split("/").last == 'sign_in?' %>
        <% else %>
          <%= button_to "sign in", new_employee_session_path, class: "signin-button", method: :get %>
        <% end%>
        <%= button_to "Create an account", new_employee_registration_path, class: "create-account-button", method: :get %>
      <%end%>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="navigation-cutom-items">
    <a class="navbar-brand ml-5" href="/">
      <img class="zensark-logo" src="https://zensark.com/zensark2/wp-content/uploads/2021/01/Asset-16.png">
    </a>
    <% if current_employee %>
      <div class="profile-container">
        <p class="profile-name">Manchala Divakar</p>
        <div class="dropdown">
          <button class="round-button" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
            <img class="profile-image" alt="dv" src="https://lh3.googleusercontent.com/ogw/ADea4I4lyuyIa0eZqz6wgpPJqJxijXM9RcK2oapYpm6T=s32-c-mo">
          </button>
          <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="#">Adminstration</a></li>
            <li><a class="dropdown-item" href="#">Manager</a></li>
            <li><%= button_to "Logout", destroy_employee_session_path, class: " dropdown-item btn btn-secondary", method: :delete%></li>
          </ul>
        </div>
      </div>
    <% else%>
    <% if request.path.split("/").last == 'sign_in' || request.path.split("/").last == 'sign_in?' %>
      <%= button_to "Home", root_path, class: "btn btn-outline-dark", method: :get %>
    <% else %>
      <%= button_to "sign in", new_employee_session_path, class: "btn btn-outline-dark mr-5", method: :get %>
    <% end%>
    <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hrmt</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= render 'layouts/navigation'%>  
    
    <%= yield %>
    
    
  </body>
</html>

app/views/pages/home.html.erb
<div class="home-main-container">
  <div class="home-card-container">
    <div class="home-descripton-container">
      <h1 class="home-heading">Secure, smart, and easy to use the Tool</h1>
      <p>Get more done with Tool. Now integrated with Tool Chat, Tool Meet, and more, all in one place.</p>
      <div>
        <button class="btn btn-primary">Get more about ZT</button>
      </div>
    </div>
    <div class="home-image-container">
    </div>
  </div>
</div>

app/views/zensark/home.html.erb
<div class="zensark-home-main-container">
  <div class="zensrk-home-left-container">
    <button class="zensark-home-left-buttons">
      Dashboard
    </button>
    <button class="zensark-home-left-buttons">
      Leaves
    </button>
    <button class="zensark-home-left-buttons">
      Attendance
    </button>
    <button class="zensark-home-left-buttons">
      Settings
    </button>
  </div>
  <div class="zensark-home-right-container">
    <div class="zensark-home-right-top-container">
      <div class="column-chart-container">
          <%= column_chart [["2021-01-01", 2], ["2021-01-02", 3],["2021-01-03", 4], ["2021-01-04", 5],["2021-01-05", 6], ["2021-01-06", 7],["2021-01-07", 8]], height: "216px" %>
      </div>
      <div class="heading-container">
        <h1 class="attendace-heading">Attendance Details</h1>
      </div>
    </div>
    <div class="zensark-home-right-bottom-container">
      <div class="zensark-home-right-bottom-left-container">
        <div class="upcoming-leaves-container">
        </div>
        <div class="heading-container">
          <h1 class="leaves-heading">Upcoming leaves</h1>
        </div>
      </div>
      <div class="zensark-home-right-bottom-right-container">
        <div>
        </div>
        <div class="heading-container">
          <h1 class="holidays-heading">Upcoming holidays</h1>
        </div>
      </div>
    </div>
  </div>
</div>